apiVersion: v1
kind: Pod
metadata:
  name: websphere
  labels: 
    name: websphere
  generateName: websphere-
spec: 
  containers: 
    - image: 172.30.92.233:5000/openshift/websphere-liberty
      name: websphere
      #env:
       # - name: TOMCAT_DB_HOST
          # this is the name of the mysql service fronting the mysql pod in the same namespace
          # expands to mysql.<namespace>.svc.cluster.local  - where <namespace> is the current namespace
          #value: mysql
      ports: 
        - containerPort: 9080
          protocol: TCP
          #name: websphere

        - containerPort: 9443
          protocol: TCP
          #name: 
      #volumeMounts:
        #- name: wordpress-persistent-storage
          #mountPath: /var/www/html
  #volumes:
    #- name: wordpress-persistent-storage
      #persistentVolumeClaim:
       #claimName: claim-wp
