apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  generateName: mysql-  
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: 172.30.92.233:5000/openshift/mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: dbpass
        - name: MYSQL_DATABASE
          value: datadb
      ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
      #volumeMounts:
        #- name: mysql-persistent-storage
          #mountPath: /var/lib/mysql/data
restartPolicy: Always
  #volumes:
    #- name: mysql-persistent-storage
      #persistentVolumeClaim:
        #claimName: claim-mysql
