apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: webfront
  name: webfront
spec: 
  ports:
    # the port that this service should serve on
    - name: "9080-tcp"
      protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 0

    - name: "9443-tcp"
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 0

  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: websphere
  #type: LoadBalancer
